title = "Aron Day"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    greeting = "Ohai."
    footer = "Created on GCP - using CI/CD pipelines!"
    author = "Aron Day"
    info = "My name is Aron . I am a SRE with Synchronoss. I do SRE/DevOps stuff."
    description = "Aron Day is a Site Relibilty Engineer with Synchronoss (SNCR). His focus is working with the DevOps community, with particular emphasis on Continuous Integration and Continuous Delivery (CI/CD)."
    keywords = "[TODO]"
    avatarurl = "img/aron-thumb.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/aronday/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/AronDayIE/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/dayaron/"

# Menu links
[[menu.main]]
    name = "Bio"
    weight = 1
    url  = "/bio/"
[[menu.main]]
    name = "Contact"
    weight = 2
    url = "/contact/"
#[[menu.main]]
#    name = "Writing"
#    weight = 3
#    url = "https://medium.com/@johndoe"
