steps:
  - name: gcr.io/$PROJECT_ID/hugo
    args: [
      "-s","hugo",
      "-d","../public"
      ]

  # create a docker container that can run on cloud run
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "tools/preview_container/Dockerfile", "-t", "gcr.io/$PROJECT_ID/site-preview:$SHORT_SHA", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","gcr.io/$PROJECT_ID/site-preview:$SHORT_SHA"]

  # deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: 
      - "-c"
      - |
        gcloud run deploy aronday-ie-preview-$SHORT_SHA --image=gcr.io/aronday-ie/site-preview:$SHORT_SHA --platform=managed --region=eu-west1 --allow-unauthenticated
        echo $(gcloud run services describe aronday-ie-preview-$SHORT_SHA --platform=managed --region=eu-west1 --format="value(status.address.url)") > /workspace/url.txt

  # add preview URL as a comment on Pull Request
  - name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args: 
      - "-c"
      - |
        # TODO: bake jq install into a builder
        apt-get update -y && apt-get install jq -y && \ 
        export PULLREQUEST_ID=$(curl "https://api.github.com/search/issues?q=$COMMIT_SHA&type:pr" | jq ".items[0].number") && \
        
        echo "{\"body\": \"Preview this revision: $(cat /workspace/url.txt)\"}" > /workspace/api_payload.txt && \

        cat /workspace/api_payload.txt && \

        # post the comment
        curl -s -H "Authorization: token $$GITHUB_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/aronday/aronday-ie/issues/$$PULLREQUEST_ID/comments"

    secretEnv: 
      - GITHUB_TOKEN

secrets:
  - kmsKeyName: projects/aronday-ie/locations/global/keyRings/aronday-ie/cryptoKeys/github-access-token
    secretEnv: 
      GITHUB_TOKEN: "\
      CiQMEf2F8+En2gZe26ebgqKyz/dPqgohP12AcnedDxRQykQ7IMwSUQDp8af+vrDXRFc34AseGbpF\
      xdDcYsPQxUYK97rM87ANDEH3IMoUZRqcIEsFn3rTs/DCTcgHLRI/t6sKomrn1bKCsHaB+QQv5aPR\
      vPyX9SYS08w=="